### ISSUE TITLE
SimpleGame demo run failed with emsdk 1.40.1 build

### ISSUE THREAD

**Issue by wqtian** [emscripten-ports/Cocos2d#1]
I build the code with latest emsdk 1.40.1 successfully. 
But I got warnning and error message while I try to run the index.html. The  detail information is as follows: 

wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
falling back to ArrayBuffer instantiation

(index):123 Uncaught TypeError: Module.callMain is not a function
    at runApplication ((index):123)
    at HTMLAnchorElement.onclick ((index):44)
![error](https://user-images.githubusercontent.com/4961247/91245959-57ea6d00-e781-11ea-9584-ddc545ca72d8.png)

**Comment by caiiiycuk** [comment]
Hi.
```
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```
Is sort of warning, to fix it you should serve wasm files with 'application/wasm' mime type. But this is not a reason why it's not working

**Comment by caiiiycuk** [comment]
This is a library project, so you can't run it as any other program, because it does not have main function. (You see error about missing main function). To use this library you should compile your program with emscripten flag `-s USE_COCOS2D=3`

**Comment by wqtian** [comment]
@caiiiycuk , 
I build the SimpleGame demo within the Cocos2d project. It reporter the warnning and error message.  I also try to build the SimpleGame demo with  emscripten flag -s USE_COCOS2D=3 directly, but it reporter the same warnning and error message.

Following is  SimpleGame's make file

[Makefile.txt](https://github.com/emscripten-ports/Cocos2d/files/5127219/Makefile.txt)

**Comment by caiiiycuk** [comment]
Maybe you can provide game sources?

**Comment by wqtian** [comment]
I use this Cocos2d samples SimpleGame. It's within this Cocos2d project. Its location is Cocos2d/samples/Cpp/SimpleGame.

**Comment by caiiiycuk** [comment]
So, in that case if you interested in sample. Please take a look on emscripten test, that used COCOS_2D:
the c++ source:
https://github.com/emscripten-core/emscripten/blob/master/tests/cocos2d_hello.cpp

the test source(build script):
https://github.com/emscripten-core/emscripten/blob/master/tests/test_browser.py#L3201

**Comment by wqtian** [comment]
OK, I will try it later. Thank you very much. 

My purpose is to test cocos2d game using wasm benchmark .  I find this project luckily, so I am trying to  build and run the game demo.

**Comment by wqtian** [comment]
@caiiiycuk , I run COCOS_2D test with
 `python3` tests/runner.py browser.test_cocos2d_hello` 

it report `cocos2d needs to be ported`.

what do i  omit?
![微信截图_20200826111609](https://user-images.githubusercontent.com/4961247/91251239-938b3400-e78d-11ea-8d7e-46bc593c25cb.png)

**Comment by caiiiycuk** [comment]
@wqtian Seems that test is not been ported to wasm backed. So you can run it only with fastcomp backend, like I do with emsdk:
```
emsdk install latest-fastcomp
emsdk activate latest-fastcomp
source emsdk_env.sh
python tests/runner.py browser.test_cocos2d_hello // (2times)

//...
----------------------------------------------------------------------
Ran 1 test in 7.534s

OK
```

**Comment by wqtian** [comment]
@caiiiycuk , thanks very much.
Do you have plan to build this Cocos2d project and sample demo with latest emscripten ?  I have tried it for days but failed. I know some build options need for adjustments. The project is a bit more complicated for me.

**Comment by caiiiycuk** [comment]
@wqtian I believe that nothing wrong with it. I used it with latest wasm backend. Just try to build
https://github.com/emscripten-core/emscripten/blob/master/tests/cocos2d_hello.cpp
without test and it should work.

**Comment by caiiiycuk** [comment]
I mean you can build cocos2d_hello.cpp with emscripten and it should work. I can check later if you have problems

**Comment by wqtian** [comment]
@caiiiycuk , I have run emscripten test  that used COCOS_2D to build cocos2d_hello.cpp successfully. It's so simple that it just launcher a webpage a few seconds and auto close. I want to do base game test which can handle keyboard input, play audio, etc.  I need build and run the SimpleGame demo successfully at least.

**Comment by caiiiycuk** [comment]
I see. But this it's demonstrates way how you should build cocos2d projects. You will need to create cmake project or Makefile that will compile only SimpleGame cpp sources.

**Comment by wqtian** [comment]
Before I have found this project, I have successfully build cocos2d-x 3.0-alpha project and run SimpleGame demo with older emscripten which only supported ASM.JS.  So I think it is possible to upgrade the emscripten to the latest to build the project and demo to wasm provided I can adjust `cocos2dx.mk` and SimpleGame's `Makefile` properly.

**Comment by caiiiycuk** [comment]
Did you solved issue?

чт, 27 авг. 2020 г. в 10:44, wqtian <notifications@github.com>:

**Comment by wqtian** [comment]
yeah, I can run SimpleGame demo successfully by modifying the SimpleGame's Makefile.
Thanks for your help.  
@caiiiycuk
